from editor import *

from editor.utils.panel_shell import PanelShell
from editor.widgets.QCustomLabels import AnimatedGradientLabel

WARNING_TEXT = (
    "Models are provided from external ports, EXcellent TechStacks "
    "does not guarantee endpoint data gathering or its safety."
)


class EtherPromptEdit(QPlainTextEdit):
    """
    Chat-style multiline prompt editor.

    The widget owns its vertical geometry. Its height is calculated from the
    actual QTextLine objects generated by Qt, so wrapped text is included.
    """

    send_requested = pyqtSignal()
    height_changed = pyqtSignal(int)

    def __init__(
        self, parent=None, *, minimum_height: int = 42, maximum_height: int = 180
    ):
        super().__init__(parent)

        self._minimum_height = minimum_height
        self._maximum_height = maximum_height

        self._desired_height = minimum_height
        self._last_width = -1
        self._updating_height = False

        self.setObjectName("EtherAIPrompt")
        self.setFrameShape(QFrame.Shape.NoFrame)
        self.setContentsMargins(0, 0, 0, 0)
        self.setViewportMargins(0, 0, 0, 0)

        self.setHorizontalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.setLineWrapMode(QPlainTextEdit.LineWrapMode.WidgetWidth)
        self.setWordWrapMode(QTextOption.WrapMode.WrapAtWordBoundaryOrAnywhere)
        self.setSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Fixed)

        self.setMinimumHeight(minimum_height)
        self.setMaximumHeight(maximum_height)
        self.setFixedHeight(minimum_height)
        self.document().contentsChanged.connect(self._queue_height_update)
        self.textChanged.connect(self._queue_height_update)

    # ------------------------------------------------------------------
    # Size handling
    # ------------------------------------------------------------------

    def sizeHint(self) -> QSize:
        return QSize(200, self._desired_height)

    def minimumSizeHint(self) -> QSize:
        return QSize(100, self._desired_height)

    def _queue_height_update(self) -> None:
        QTimer.singleShot(0, self._update_height)

    def _available_text_width(self) -> int:
        width = self.viewport().width()
        if width > 0:
            return width

        return max(1, self.width() - self.frameWidth() * 2)

    def _calculate_document_height(self) -> float:
        document = self.document()
        text_width = self._available_text_width()
        document.setTextWidth(text_width)
        layout = document.documentLayout()

        layout.documentSize()
        total_height = 0.0
        block = document.begin()

        while block.isValid():
            block_layout = block.layout()

            if block_layout is not None:
                line_count = block_layout.lineCount()

                if line_count == 0:
                    total_height += self.fontMetrics().lineSpacing()
                else:
                    for index in range(line_count):
                        line = block_layout.lineAt(index)
                        total_height += line.height()

            block = block.next()

        if total_height <= 0:
            total_height = self.fontMetrics().lineSpacing()

        total_height += document.documentMargin() * 2

        return total_height

    def _calculate_desired_height(self) -> int:
        document_height = self._calculate_document_height()
        extra = 10
        height = int(document_height + extra)

        return max(
            self._minimum_height,
            min(
                self._maximum_height,
                height,
            ),
        )

    def _update_height(self) -> None:
        if self._updating_height:
            return

        if not self.isVisible():
            return

        width = self._available_text_width()

        if width <= 1:
            return
        self._updating_height = True

        try:
            new_height = self._calculate_desired_height()
            document_height = self._calculate_document_height()
            exceeds_maximum = document_height + 10 > self._maximum_height
            if exceeds_maximum:
                self.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAsNeeded)
            else:
                self.setVerticalScrollBarPolicy(Qt.ScrollBarPolicy.ScrollBarAlwaysOff)

            changed = new_height != self._desired_height
            width_changed = width != self._last_width
            self._desired_height = new_height
            self._last_width = width

            self.setMinimumHeight(new_height)
            self.setMaximumHeight(new_height)
            self.setFixedHeight(new_height)
            self.updateGeometry()

            if changed or width_changed:
                self.height_changed.emit(new_height)

            self._activate_parent_layouts()

        finally:
            self._updating_height = False

    def _activate_parent_layouts(self) -> None:
        """
        Force every parent layout to process the new geometry immediately.
        """
        widget = self.parentWidget()
        while widget is not None:
            layout = widget.layout()

            if layout is not None:
                layout.invalidate()
                layout.activate()

            widget.updateGeometry()

            widget = widget.parentWidget()

    # ------------------------------------------------------------------
    # Qt events
    # ------------------------------------------------------------------

    def showEvent(self, event):
        super().showEvent(event)
        QTimer.singleShot(0, self._update_height)

    def resizeEvent(self, event):
        super().resizeEvent(event)
        QTimer.singleShot(0, self._update_height)

    def keyPressEvent(self, event):
        if event.key() in (
            Qt.Key.Key_Return,
            Qt.Key.Key_Enter,
        ) and not (event.modifiers() & Qt.KeyboardModifier.ShiftModifier):
            self.send_requested.emit()
            event.accept()
            return

        super().keyPressEvent(event)

        QTimer.singleShot(0, self._update_height)


class EtherComposer(QFrame):
    """
    Self-sizing AI composer.

    The composer height is controlled explicitly from the prompt height,
    rather than asking QLayout to infer it.
    """

    send_requested = pyqtSignal()

    def __init__(self, parent=None):
        super().__init__(parent)

        self.setObjectName("EtherComposer")

        self.setSizePolicy(
            QSizePolicy.Policy.Expanding,
            QSizePolicy.Policy.Fixed,
        )

        self._layout = QVBoxLayout(self)

        self._layout.setContentsMargins(10, 10, 10, 9)

        self._layout.setSpacing(6)
        self.prompt = EtherPromptEdit(self, minimum_height=42, maximum_height=180)
        self.send_button = QPushButton("Send", self)
        self.send_button.setObjectName("EtherSendButton")
        self.send_button.setFixedSize(76, 32)

        self.send_button.setCursor(Qt.CursorShape.PointingHandCursor)
        self.send_button.setFocusPolicy(Qt.FocusPolicy.NoFocus)
        self._button_layout = QHBoxLayout()
        self._button_layout.setContentsMargins(0, 0, 0, 0)

        self._button_layout.setSpacing(0)
        self._button_layout.addStretch(1)
        self._button_layout.addWidget(self.send_button)
        self._layout.addWidget(self.prompt, 0, Qt.AlignmentFlag.AlignTop)

        self._layout.addLayout(self._button_layout)
        self.prompt.send_requested.connect(self._handle_send)
        self.send_button.clicked.connect(self._handle_send)
        self.prompt.textChanged.connect(self._update_send_button)
        self.prompt.height_changed.connect(self._resize_from_prompt)
        self._update_send_button()
        QTimer.singleShot(0, self._sync_height)

    # ------------------------------------------------------------------
    # Geometry
    # ------------------------------------------------------------------

    def sizeHint(self) -> QSize:
        return QSize(400, self._calculate_height())

    def minimumSizeHint(self) -> QSize:
        return QSize(200, self._calculate_height())

    def _calculate_height(self) -> int:
        margins = self._layout.contentsMargins()

        return (
            margins.top()
            + self.prompt.height()
            + self._layout.spacing()
            + self.send_button.height()
            + margins.bottom()
        )

    def _resize_from_prompt(self, _height: int) -> None:
        self._sync_height()

    def _sync_height(self) -> None:
        height = self._calculate_height()

        self.setMinimumHeight(height)
        self.setMaximumHeight(height)
        self.setFixedHeight(height)
        self.updateGeometry()

        parent = self.parentWidget()

        while parent is not None:
            layout = parent.layout()

            if layout is not None:
                layout.invalidate()
                layout.activate()

            parent.updateGeometry()
            parent = parent.parentWidget()

    # ------------------------------------------------------------------
    # Sending
    # ------------------------------------------------------------------

    def _handle_send(self) -> None:
        text = self.prompt.toPlainText().strip()
        if not text:
            return
        self.send_requested.emit()

    def _update_send_button(self) -> None:
        self.send_button.setEnabled(bool(self.prompt.toPlainText().strip()))

    # ------------------------------------------------------------------
    # Theme
    # ------------------------------------------------------------------

    def set_theme(self, bg: str, fg: str, sel: str) -> None:
        self.setStyleSheet(f"""
            QFrame#EtherComposer {{
                background: {bg};
                border: 1px solid palette(mid);
                border-radius: 14px;
            }}

            QPlainTextEdit#EtherAIPrompt {{
                background: transparent;
                border: none;
                padding: 2px 4px;
                color: {fg};
                selection-background-color: {sel};
                selection-color: palette(highlightedText);
                font-size: 14px;
            }}

            QPlainTextEdit#EtherAIPrompt:focus {{
                border: none;
                outline: none;
            }}

            QPushButton#EtherSendButton {{
                background: palette(highlight);
                border: 1px solid palette(highlight);
                border-radius: 9px;
                color: palette(highlightedText);
                font-size: 13px;
                font-weight: 600;
                padding: 0px;
            }}

            QPushButton#EtherSendButton:hover {{
                background: palette(highlight);
            }}

            QPushButton#EtherSendButton:pressed {{
                background: palette(mid);
                border-color: palette(mid);
            }}

            QPushButton#EtherSendButton:disabled {{
                background: palette(mid);
                border-color: palette(mid);
                color: palette(midlight);
            }}
            """)


class EtherSuggestionButton(QPushButton):
    """
    Prompt suggestion button.
    """

    def __init__(
        self,
        text: str,
        parent=None,
    ):
        super().__init__(
            text,
            parent,
        )

        self.setObjectName("EtherSuggestion")
        self.setFixedHeight(40)
        self.setCursor(Qt.CursorShape.PointingHandCursor)
        self.setSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Fixed)


class MainScreen(QFrame):
    """
    Main Ether AI interface.
    """

    send_requested = pyqtSignal()

    def __init__(self, master=None):
        super().__init__(master)
        self._active = False

        self.setFrameShape(QFrame.Shape.NoFrame)
        self.setSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)

        self._build_ui()
        self._connect_signals()
        self._build_animations()
        self._apply_default_theme()

    # ------------------------------------------------------------------
    # UI
    # ------------------------------------------------------------------

    def _build_ui(self) -> None:
        self._layout = QVBoxLayout(self)
        self._layout.setContentsMargins(18, 18, 18, 18)

        self._layout.setSpacing(0)

        # --------------------------------------------------------------
        # Header
        # --------------------------------------------------------------

        self.welcome_message = AnimatedGradientLabel("Hi, DreamStudio Developer", self)

        self.welcome_message.setStyleSheet("""
            font-size: 30px;
            font-weight: 600;
            background: transparent;
            """)

        self._layout.addWidget(self.welcome_message)

        self.sub_text = QLabel("Ready to start creating?", self)

        self.sub_text.setObjectName("EtherSubtitle")
        self._layout.addWidget(self.sub_text)

        # --------------------------------------------------------------
        # Flexible space
        # --------------------------------------------------------------

        self._layout.addStretch(1)

        # --------------------------------------------------------------
        # Composer
        # --------------------------------------------------------------

        self.composer = EtherComposer(self)

        self._layout.addWidget(self.composer, 0, Qt.AlignmentFlag.AlignBottom)

        # --------------------------------------------------------------
        # Suggestions
        # --------------------------------------------------------------

        self._layout.addSpacing(24)

        self.features_label = QLabel("Try these prompts first", self)

        self.features_label.setObjectName("EtherSectionTitle")
        self._layout.addWidget(self.features_label)
        self._layout.addSpacing(9)
        self.fix_issues_prompt = EtherSuggestionButton(
            "Review my code in the current file", self
        )
        self.add_documentation_prompt = EtherSuggestionButton(
            "Add documentation to this file's methods and classes", self
        )

        self._layout.addWidget(self.fix_issues_prompt)
        self._layout.addSpacing(7)
        self._layout.addWidget(self.add_documentation_prompt)

        # --------------------------------------------------------------
        # Bottom space
        # --------------------------------------------------------------

        self._layout.addStretch(1)

        # --------------------------------------------------------------
        # Warning
        # --------------------------------------------------------------

        self.warnings_label = QLabel(WARNING_TEXT, self)

        self.warnings_label.setObjectName("EtherWarning")
        self.warnings_label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.warnings_label.setWordWrap(True)
        self._layout.addWidget(self.warnings_label)

    # ------------------------------------------------------------------
    # Connections
    # ------------------------------------------------------------------

    def _connect_signals(self) -> None:
        self.composer.send_requested.connect(self._on_send)
        self.fix_issues_prompt.clicked.connect(
            lambda: self._use_suggestion(self.fix_issues_prompt.text())
        )
        self.add_documentation_prompt.clicked.connect(
            lambda: self._use_suggestion(self.add_documentation_prompt.text())
        )

    def _on_send(self) -> None:
        prompt = self.composer.prompt.toPlainText().strip()
        if not prompt:
            return

        self.send_requested.emit()

    def _use_suggestion(self, text: str) -> None:
        prompt = self.composer.prompt

        prompt.setPlainText(text)
        prompt.moveCursor(QTextCursor.MoveOperation.End)
        prompt.setFocus()
        QTimer.singleShot(0, prompt._update_height)

    # ------------------------------------------------------------------
    # Animation
    # ------------------------------------------------------------------

    def _build_animations(self) -> None:
        self._subtitle_effect = QGraphicsOpacityEffect(self.sub_text)
        self.sub_text.setGraphicsEffect(self._subtitle_effect)
        self._composer_effect = QGraphicsOpacityEffect(self.composer)
        self.composer.setGraphicsEffect(self._composer_effect)
        self._suggestions_effect = QGraphicsOpacityEffect(self.features_label)
        self.features_label.setGraphicsEffect(self._suggestions_effect)
        self._warning_effect = QGraphicsOpacityEffect(self.warnings_label)
        self.warnings_label.setGraphicsEffect(self._warning_effect)

        self._animations = []

        for effect, duration in (
            (self._subtitle_effect, 260),
            (self._composer_effect, 360),
            (self._suggestions_effect, 420),
            (self._warning_effect, 500),
        ):
            animation = QPropertyAnimation(effect, b"opacity", self)

            animation.setDuration(duration)
            animation.setEasingCurve(QEasingCurve.Type.OutCubic)
            self._animations.append(animation)

    def _animate_in(self) -> None:
        self.welcome_message.start_animation()

        effects = (
            self._subtitle_effect,
            self._composer_effect,
            self._suggestions_effect,
            self._warning_effect,
        )

        for animation, effect in zip(self._animations, effects):
            animation.stop()
            animation.setStartValue(0.0)
            animation.setEndValue(1.0)
            animation.start()

    def _animate_out(self) -> None:
        self.welcome_message.stop_animation()

    # ------------------------------------------------------------------
    # Theme
    # ------------------------------------------------------------------

    def _apply_default_theme(self) -> None:
        self.setStyleSheet("""
            QLabel#EtherSubtitle {
                color: #9AA0A6;
                font-size: 18px;
                background: transparent;
            }

            QLabel#EtherSectionTitle {
                color: palette(text);
                font-size: 17px;
                font-weight: 600;
                background: transparent;
            }

            QLabel#EtherWarning {
                color: #A5A5A5;
                font-size: 11px;
                background: transparent;
            }

            QPushButton#EtherSuggestion {
                text-align: left;
                border: 1px solid palette(mid);
                border-radius: 10px;
                padding: 0px 14px;
                background: transparent;
                color: palette(text);
            }

            QPushButton#EtherSuggestion:hover {
                border: 1px solid palette(highlight);
                background: palette(highlight);
                color: palette(highlightedText);
            }

            QPushButton#EtherSuggestion:pressed {
                border: 1px solid palette(highlight);
                background: palette(mid);
                color: palette(highlightedText);
            }
            """)

        self.composer.set_theme(
            "palette(base)",
            "palette(text)",
            "palette(highlight)",
        )

    def set_theme(self, bg: str, fg: str, sel: str) -> None:
        self.setStyleSheet(f"""
            QLabel#EtherSubtitle {{
                color: {fg};
                font-size: 18px;
                background: transparent;
            }}

            QLabel#EtherSectionTitle {{
                color: {fg};
                font-size: 17px;
                font-weight: 600;
                background: transparent;
            }}

            QLabel#EtherWarning {{
                color: {fg};
                font-size: 11px;
                background: transparent;
            }}

            QPushButton#EtherSuggestion {{
                text-align: left;
                border: 1px solid palette(mid);
                border-radius: 10px;
                padding: 0px 14px;
                background: transparent;
                color: {fg};
            }}

            QPushButton#EtherSuggestion:hover {{
                border: 1px solid palette(highlight);
                background: palette(highlight);
                color: {fg};
            }}

            QPushButton#EtherSuggestion:pressed {{
                border: 1px solid palette(highlight);
                background: palette(mid);
                color: {fg};
            }}
            """)

        self.composer.set_theme(bg, fg, sel)

    # ------------------------------------------------------------------
    # Visibility / activation
    # ------------------------------------------------------------------

    def showEvent(self, event):
        super().showEvent(event)
        QTimer.singleShot(0, self._activate)

    def resizeEvent(self, event):
        super().resizeEvent(event)

        active = event.size().width() > 10
        if active != self._active:
            self._set_active(active)

    def _activate(self) -> None:
        if self.width() > 10:
            self._set_active(True)

    def _set_active(self, active: bool) -> None:
        self._active = active

        if active:
            self._animate_in()
        else:
            self._animate_out()


class EtherAI(PanelShell):
    """
    PanelShell wrapper for Ether AI.
    """

    PANEL_OBJECT_NAME = "EtherAI"
    FRAME_OBJECT_NAME = "EtherAIFrame"
    TITLE_OBJECT_NAME = "EtherAITitle"
    TITLE_TEXT = "Ether AI"

    def __init__(self, parent=None):
        self._ether_screen: MainScreen | None = None

        super().__init__(parent)

        self.setMinimumWidth(450)

    def _build_body(self) -> None:
        self._ether_screen = MainScreen(self)

        self._ether_screen.setSizePolicy(
            QSizePolicy.Policy.Expanding,
            QSizePolicy.Policy.Expanding,
        )

        self._frame_layout.addWidget(self._ether_screen)

    def _header_right_widgets(self) -> list[QWidget]:
        return []

    def set_theme(self, bg: str, fg: str, sel: str) -> None:
        if self._ether_screen is not None:
            self._ether_screen.set_theme(bg, fg, sel)
