# Project Type: Empty Project
# COPYRIGHT 2026 - EXcellent TechStacks Projects Initializers
languages: ["python", "clang"]
version: "studio_default_version"
interpreter_location: "studio_interpreter_defined_location"

project_type: "pi_ai_project"
display_name: "Raspberry Pi Machine Learning Project"
description: |
  Develop a machine learning service on the Raspberry Pi using Python packages 
  such as scikit-learn, NumPy, and Seaborn. 

initialization: 
  directories: 
    - "iot-devkit"
    - "include"
    - "src"
    - "tests"
    - "build"
  files: 
    - ".gitignore"
    - "config.toml"
    - "README.md"
    - "requirements.txt"
    - "clang_required.bash"
    - "src/train.py"
  templates: 
    - target: "src/train.py"
      contents: |
        def main():
            print("Project initialized successfully.")

        if __name__ == "__main__":
            main()
    - target: "requirements.txt"
      contents: |
        # Core third-party dependencies go here.
        pytest>=8.0.0
        paho-mqtt
        requests
        numpy
        scikit-learn
        matplotlib
        seaborn
        pandas

    - target: ".gitignore"
      contents: |
        # Byte-compiled / optimized / DLL files
        __pycache__/
        *.py[cod]
        *$py.class

        # C extensions
        *.so

        # Distribution / packaging
        .Python
        build/
        develop-eggs/
        dist/
        downloads/
        eggs/
        .eggs/
        lib/
        lib64/
        parts/
        sdist/
        var/
        wheels/
        *.egg-info/

        # Virtual Environments
        venv/
        .venv/
        env/
        
        # IDE Specific Configurations
        .idea/
        .vscode/
        *.studio

post_lifecycle:
  - step: "create_venv"
    desc: "Creating isolated virtual environment"
    unix: "python3 -m venv venv"
    wind: "python -m venv venv"
  - step: "install_dependencies"
    desc: "Installing structural project base components"
    unix: "./venv/bin/pip install -r requirements.txt"
    wind: ".\\venv\\Scripts\\pip.exe install -r requirements.txt"