//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Lavender.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="ILavenderListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class LavenderBaseListener : ILavenderListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="LavenderParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProgram([NotNull] LavenderParser.ProgramContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LavenderParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProgram([NotNull] LavenderParser.ProgramContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LavenderParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatement([NotNull] LavenderParser.StatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LavenderParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatement([NotNull] LavenderParser.StatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LavenderParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpr([NotNull] LavenderParser.ExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LavenderParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpr([NotNull] LavenderParser.ExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LavenderParser.declareVar"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDeclareVar([NotNull] LavenderParser.DeclareVarContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LavenderParser.declareVar"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDeclareVar([NotNull] LavenderParser.DeclareVarContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LavenderParser.assignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssignment([NotNull] LavenderParser.AssignmentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LavenderParser.assignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssignment([NotNull] LavenderParser.AssignmentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LavenderParser.funcCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFuncCall([NotNull] LavenderParser.FuncCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LavenderParser.funcCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFuncCall([NotNull] LavenderParser.FuncCallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LavenderParser.condition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCondition([NotNull] LavenderParser.ConditionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LavenderParser.condition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCondition([NotNull] LavenderParser.ConditionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LavenderParser.loop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLoop([NotNull] LavenderParser.LoopContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LavenderParser.loop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLoop([NotNull] LavenderParser.LoopContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="LavenderParser.commandStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCommandStatement([NotNull] LavenderParser.CommandStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="LavenderParser.commandStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCommandStatement([NotNull] LavenderParser.CommandStatementContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
