//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Lavender.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="LavenderParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface ILavenderListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="LavenderParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProgram([NotNull] LavenderParser.ProgramContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LavenderParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProgram([NotNull] LavenderParser.ProgramContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LavenderParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] LavenderParser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LavenderParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] LavenderParser.StatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LavenderParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpr([NotNull] LavenderParser.ExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LavenderParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpr([NotNull] LavenderParser.ExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LavenderParser.declareVar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclareVar([NotNull] LavenderParser.DeclareVarContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LavenderParser.declareVar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclareVar([NotNull] LavenderParser.DeclareVarContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LavenderParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignment([NotNull] LavenderParser.AssignmentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LavenderParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignment([NotNull] LavenderParser.AssignmentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LavenderParser.funcCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFuncCall([NotNull] LavenderParser.FuncCallContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LavenderParser.funcCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFuncCall([NotNull] LavenderParser.FuncCallContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LavenderParser.condition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCondition([NotNull] LavenderParser.ConditionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LavenderParser.condition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCondition([NotNull] LavenderParser.ConditionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LavenderParser.loop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLoop([NotNull] LavenderParser.LoopContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LavenderParser.loop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLoop([NotNull] LavenderParser.LoopContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="LavenderParser.commandStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCommandStatement([NotNull] LavenderParser.CommandStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="LavenderParser.commandStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCommandStatement([NotNull] LavenderParser.CommandStatementContext context);
}
