//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Lavender.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public partial class LavenderParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		IF=1, ELIF=2, ELSE=3, DO=4, WHILE=5, PRINT=6, INPUT=7, VARIABLE=8, FUNCTION=9, 
		METHOD=10, MACRO=11, CLASS=12, NAMESPC=13, BOOL=14, UINT=15, SINT=16, 
		UFLOAT=17, SFLOAT=18, STRING=19, CHAR=20, UBINARY=21, SBINARY=22, UHEX=23, 
		SHEX=24, PLUS=25, MINUS=26, MULT=27, DIVD=28, POWER=29, MODULUS=30, EQUAL=31, 
		NOTEQ=32, ASSIGN=33, LESS=34, BIGGER=35, LESSEQ=36, BIGGEREQ=37, LPAREN=38, 
		RPAREN=39, LBRACE=40, RBRACE=41, SEMI=42, COMMA=43, IDENTIFY=44, WS=45, 
		COMMENT=46, MULTICOM=47;
	public const int
		RULE_program = 0, RULE_statement = 1, RULE_expr = 2, RULE_declareVar = 3, 
		RULE_assignment = 4, RULE_funcCall = 5, RULE_condition = 6, RULE_loop = 7, 
		RULE_commandStatement = 8;
	public static readonly string[] ruleNames = {
		"program", "statement", "expr", "declareVar", "assignment", "funcCall", 
		"condition", "loop", "commandStatement"
	};

	private static readonly string[] _LiteralNames = {
		null, "'if'", null, "'else'", "'do'", "'while'", null, null, null, null, 
		null, "'macro'", "'class'", "'namespace'", null, null, null, null, null, 
		null, null, null, null, null, null, "'+'", "'-'", "'*'", "'/'", "'^'", 
		"'%'", "'=='", "'!=='", "'='", "'<'", "'>'", "'<='", "'>='", "'('", "')'", 
		"'{'", "'}'", "';'", "','"
	};
	private static readonly string[] _SymbolicNames = {
		null, "IF", "ELIF", "ELSE", "DO", "WHILE", "PRINT", "INPUT", "VARIABLE", 
		"FUNCTION", "METHOD", "MACRO", "CLASS", "NAMESPC", "BOOL", "UINT", "SINT", 
		"UFLOAT", "SFLOAT", "STRING", "CHAR", "UBINARY", "SBINARY", "UHEX", "SHEX", 
		"PLUS", "MINUS", "MULT", "DIVD", "POWER", "MODULUS", "EQUAL", "NOTEQ", 
		"ASSIGN", "LESS", "BIGGER", "LESSEQ", "BIGGEREQ", "LPAREN", "RPAREN", 
		"LBRACE", "RBRACE", "SEMI", "COMMA", "IDENTIFY", "WS", "COMMENT", "MULTICOM"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "Lavender.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static LavenderParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public LavenderParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public LavenderParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class ProgramContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Eof() { return GetToken(LavenderParser.Eof, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public StatementContext[] statement() {
			return GetRuleContexts<StatementContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public StatementContext statement(int i) {
			return GetRuleContext<StatementContext>(i);
		}
		public ProgramContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_program; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ILavenderListener typedListener = listener as ILavenderListener;
			if (typedListener != null) typedListener.EnterProgram(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ILavenderListener typedListener = listener as ILavenderListener;
			if (typedListener != null) typedListener.ExitProgram(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILavenderVisitor<TResult> typedVisitor = visitor as ILavenderVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitProgram(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ProgramContext program() {
		ProgramContext _localctx = new ProgramContext(Context, State);
		EnterRule(_localctx, 0, RULE_program);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 19;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				{
				State = 18;
				statement();
				}
				}
				State = 21;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( (((_la) & ~0x3f) == 0 && ((1L << _la) & 17592186045298L) != 0) );
			State = 23;
			Match(Eof);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StatementContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public DeclareVarContext declareVar() {
			return GetRuleContext<DeclareVarContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public AssignmentContext assignment() {
			return GetRuleContext<AssignmentContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ConditionContext condition() {
			return GetRuleContext<ConditionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public LoopContext loop() {
			return GetRuleContext<LoopContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public CommandStatementContext commandStatement() {
			return GetRuleContext<CommandStatementContext>(0);
		}
		public StatementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_statement; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ILavenderListener typedListener = listener as ILavenderListener;
			if (typedListener != null) typedListener.EnterStatement(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ILavenderListener typedListener = listener as ILavenderListener;
			if (typedListener != null) typedListener.ExitStatement(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILavenderVisitor<TResult> typedVisitor = visitor as ILavenderVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitStatement(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public StatementContext statement() {
		StatementContext _localctx = new StatementContext(Context, State);
		EnterRule(_localctx, 2, RULE_statement);
		try {
			State = 30;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case VARIABLE:
				EnterOuterAlt(_localctx, 1);
				{
				State = 25;
				declareVar();
				}
				break;
			case IDENTIFY:
				EnterOuterAlt(_localctx, 2);
				{
				State = 26;
				assignment();
				}
				break;
			case IF:
				EnterOuterAlt(_localctx, 3);
				{
				State = 27;
				condition();
				}
				break;
			case DO:
			case WHILE:
				EnterOuterAlt(_localctx, 4);
				{
				State = 28;
				loop();
				}
				break;
			case PRINT:
			case FUNCTION:
				EnterOuterAlt(_localctx, 5);
				{
				State = 29;
				commandStatement();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ExprContext : ParserRuleContext {
		public IToken op;
		[System.Diagnostics.DebuggerNonUserCode] public FuncCallContext funcCall() {
			return GetRuleContext<FuncCallContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode UINT() { return GetToken(LavenderParser.UINT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SINT() { return GetToken(LavenderParser.SINT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode UFLOAT() { return GetToken(LavenderParser.UFLOAT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SFLOAT() { return GetToken(LavenderParser.SFLOAT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRING() { return GetToken(LavenderParser.STRING, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CHAR() { return GetToken(LavenderParser.CHAR, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode BOOL() { return GetToken(LavenderParser.BOOL, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode UBINARY() { return GetToken(LavenderParser.UBINARY, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SBINARY() { return GetToken(LavenderParser.SBINARY, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode UHEX() { return GetToken(LavenderParser.UHEX, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SHEX() { return GetToken(LavenderParser.SHEX, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENTIFY() { return GetToken(LavenderParser.IDENTIFY, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LPAREN() { return GetToken(LavenderParser.LPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RPAREN() { return GetToken(LavenderParser.RPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LBRACE() { return GetToken(LavenderParser.LBRACE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RBRACE() { return GetToken(LavenderParser.RBRACE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode MULT() { return GetToken(LavenderParser.MULT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DIVD() { return GetToken(LavenderParser.DIVD, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode PLUS() { return GetToken(LavenderParser.PLUS, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode MINUS() { return GetToken(LavenderParser.MINUS, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode EQUAL() { return GetToken(LavenderParser.EQUAL, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NOTEQ() { return GetToken(LavenderParser.NOTEQ, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode BIGGER() { return GetToken(LavenderParser.BIGGER, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LESS() { return GetToken(LavenderParser.LESS, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode BIGGEREQ() { return GetToken(LavenderParser.BIGGEREQ, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LESSEQ() { return GetToken(LavenderParser.LESSEQ, 0); }
		public ExprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expr; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ILavenderListener typedListener = listener as ILavenderListener;
			if (typedListener != null) typedListener.EnterExpr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ILavenderListener typedListener = listener as ILavenderListener;
			if (typedListener != null) typedListener.ExitExpr(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILavenderVisitor<TResult> typedVisitor = visitor as ILavenderVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitExpr(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ExprContext expr() {
		return expr(0);
	}

	private ExprContext expr(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		ExprContext _localctx = new ExprContext(Context, _parentState);
		ExprContext _prevctx = _localctx;
		int _startState = 4;
		EnterRecursionRule(_localctx, 4, RULE_expr, _p);
		int _la;
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 54;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,2,Context) ) {
			case 1:
				{
				State = 33;
				funcCall();
				}
				break;
			case 2:
				{
				State = 34;
				Match(UINT);
				}
				break;
			case 3:
				{
				State = 35;
				Match(SINT);
				}
				break;
			case 4:
				{
				State = 36;
				Match(UFLOAT);
				}
				break;
			case 5:
				{
				State = 37;
				Match(SFLOAT);
				}
				break;
			case 6:
				{
				State = 38;
				Match(STRING);
				}
				break;
			case 7:
				{
				State = 39;
				Match(CHAR);
				}
				break;
			case 8:
				{
				State = 40;
				Match(BOOL);
				}
				break;
			case 9:
				{
				State = 41;
				Match(UBINARY);
				}
				break;
			case 10:
				{
				State = 42;
				Match(SBINARY);
				}
				break;
			case 11:
				{
				State = 43;
				Match(UHEX);
				}
				break;
			case 12:
				{
				State = 44;
				Match(SHEX);
				}
				break;
			case 13:
				{
				State = 45;
				Match(IDENTIFY);
				}
				break;
			case 14:
				{
				State = 46;
				Match(LPAREN);
				State = 47;
				expr(0);
				State = 48;
				Match(RPAREN);
				}
				break;
			case 15:
				{
				State = 50;
				Match(LBRACE);
				State = 51;
				expr(0);
				State = 52;
				Match(RBRACE);
				}
				break;
			}
			Context.Stop = TokenStream.LT(-1);
			State = 70;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,4,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null )
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					State = 68;
					ErrorHandler.Sync(this);
					switch ( Interpreter.AdaptivePredict(TokenStream,3,Context) ) {
					case 1:
						{
						_localctx = new ExprContext(_parentctx, _parentState);
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 56;
						if (!(Precpred(Context, 4))) throw new FailedPredicateException(this, "Precpred(Context, 4)");
						State = 57;
						_localctx.op = TokenStream.LT(1);
						_la = TokenStream.LA(1);
						if ( !(_la==MULT || _la==DIVD) ) {
							_localctx.op = ErrorHandler.RecoverInline(this);
						}
						else {
							ErrorHandler.ReportMatch(this);
						    Consume();
						}
						State = 58;
						expr(5);
						}
						break;
					case 2:
						{
						_localctx = new ExprContext(_parentctx, _parentState);
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 59;
						if (!(Precpred(Context, 3))) throw new FailedPredicateException(this, "Precpred(Context, 3)");
						State = 60;
						_localctx.op = TokenStream.LT(1);
						_la = TokenStream.LA(1);
						if ( !(_la==PLUS || _la==MINUS) ) {
							_localctx.op = ErrorHandler.RecoverInline(this);
						}
						else {
							ErrorHandler.ReportMatch(this);
						    Consume();
						}
						State = 61;
						expr(4);
						}
						break;
					case 3:
						{
						_localctx = new ExprContext(_parentctx, _parentState);
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 62;
						if (!(Precpred(Context, 2))) throw new FailedPredicateException(this, "Precpred(Context, 2)");
						State = 63;
						_localctx.op = TokenStream.LT(1);
						_la = TokenStream.LA(1);
						if ( !(_la==EQUAL || _la==NOTEQ) ) {
							_localctx.op = ErrorHandler.RecoverInline(this);
						}
						else {
							ErrorHandler.ReportMatch(this);
						    Consume();
						}
						State = 64;
						expr(3);
						}
						break;
					case 4:
						{
						_localctx = new ExprContext(_parentctx, _parentState);
						PushNewRecursionContext(_localctx, _startState, RULE_expr);
						State = 65;
						if (!(Precpred(Context, 1))) throw new FailedPredicateException(this, "Precpred(Context, 1)");
						State = 66;
						_localctx.op = TokenStream.LT(1);
						_la = TokenStream.LA(1);
						if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & 257698037760L) != 0)) ) {
							_localctx.op = ErrorHandler.RecoverInline(this);
						}
						else {
							ErrorHandler.ReportMatch(this);
						    Consume();
						}
						State = 67;
						expr(2);
						}
						break;
					}
					} 
				}
				State = 72;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,4,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public partial class DeclareVarContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode VARIABLE() { return GetToken(LavenderParser.VARIABLE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENTIFY() { return GetToken(LavenderParser.IDENTIFY, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SEMI() { return GetToken(LavenderParser.SEMI, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ASSIGN() { return GetToken(LavenderParser.ASSIGN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public DeclareVarContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_declareVar; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ILavenderListener typedListener = listener as ILavenderListener;
			if (typedListener != null) typedListener.EnterDeclareVar(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ILavenderListener typedListener = listener as ILavenderListener;
			if (typedListener != null) typedListener.ExitDeclareVar(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILavenderVisitor<TResult> typedVisitor = visitor as ILavenderVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDeclareVar(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public DeclareVarContext declareVar() {
		DeclareVarContext _localctx = new DeclareVarContext(Context, State);
		EnterRule(_localctx, 6, RULE_declareVar);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 73;
			Match(VARIABLE);
			State = 74;
			Match(IDENTIFY);
			State = 77;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==ASSIGN) {
				{
				State = 75;
				Match(ASSIGN);
				State = 76;
				expr(0);
				}
			}

			State = 79;
			Match(SEMI);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class AssignmentContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENTIFY() { return GetToken(LavenderParser.IDENTIFY, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ASSIGN() { return GetToken(LavenderParser.ASSIGN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SEMI() { return GetToken(LavenderParser.SEMI, 0); }
		public AssignmentContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_assignment; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ILavenderListener typedListener = listener as ILavenderListener;
			if (typedListener != null) typedListener.EnterAssignment(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ILavenderListener typedListener = listener as ILavenderListener;
			if (typedListener != null) typedListener.ExitAssignment(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILavenderVisitor<TResult> typedVisitor = visitor as ILavenderVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAssignment(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public AssignmentContext assignment() {
		AssignmentContext _localctx = new AssignmentContext(Context, State);
		EnterRule(_localctx, 8, RULE_assignment);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 81;
			Match(IDENTIFY);
			State = 82;
			Match(ASSIGN);
			State = 83;
			expr(0);
			State = 84;
			Match(SEMI);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FuncCallContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENTIFY() { return GetToken(LavenderParser.IDENTIFY, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LPAREN() { return GetToken(LavenderParser.LPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RPAREN() { return GetToken(LavenderParser.RPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] COMMA() { return GetTokens(LavenderParser.COMMA); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COMMA(int i) {
			return GetToken(LavenderParser.COMMA, i);
		}
		public FuncCallContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_funcCall; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ILavenderListener typedListener = listener as ILavenderListener;
			if (typedListener != null) typedListener.EnterFuncCall(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ILavenderListener typedListener = listener as ILavenderListener;
			if (typedListener != null) typedListener.ExitFuncCall(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILavenderVisitor<TResult> typedVisitor = visitor as ILavenderVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFuncCall(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public FuncCallContext funcCall() {
		FuncCallContext _localctx = new FuncCallContext(Context, State);
		EnterRule(_localctx, 10, RULE_funcCall);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 86;
			Match(IDENTIFY);
			State = 87;
			Match(LPAREN);
			State = 96;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if ((((_la) & ~0x3f) == 0 && ((1L << _la) & 18966609117184L) != 0)) {
				{
				State = 88;
				expr(0);
				State = 93;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==COMMA) {
					{
					{
					State = 89;
					Match(COMMA);
					State = 90;
					expr(0);
					}
					}
					State = 95;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				}
			}

			State = 98;
			Match(RPAREN);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ConditionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IF() { return GetToken(LavenderParser.IF, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] LPAREN() { return GetTokens(LavenderParser.LPAREN); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LPAREN(int i) {
			return GetToken(LavenderParser.LPAREN, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] RPAREN() { return GetTokens(LavenderParser.RPAREN); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RPAREN(int i) {
			return GetToken(LavenderParser.RPAREN, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] LBRACE() { return GetTokens(LavenderParser.LBRACE); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LBRACE(int i) {
			return GetToken(LavenderParser.LBRACE, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] RBRACE() { return GetTokens(LavenderParser.RBRACE); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RBRACE(int i) {
			return GetToken(LavenderParser.RBRACE, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public StatementContext[] statement() {
			return GetRuleContexts<StatementContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public StatementContext statement(int i) {
			return GetRuleContext<StatementContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] ELIF() { return GetTokens(LavenderParser.ELIF); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ELIF(int i) {
			return GetToken(LavenderParser.ELIF, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ELSE() { return GetToken(LavenderParser.ELSE, 0); }
		public ConditionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_condition; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ILavenderListener typedListener = listener as ILavenderListener;
			if (typedListener != null) typedListener.EnterCondition(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ILavenderListener typedListener = listener as ILavenderListener;
			if (typedListener != null) typedListener.ExitCondition(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILavenderVisitor<TResult> typedVisitor = visitor as ILavenderVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCondition(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ConditionContext condition() {
		ConditionContext _localctx = new ConditionContext(Context, State);
		EnterRule(_localctx, 12, RULE_condition);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 100;
			Match(IF);
			State = 101;
			Match(LPAREN);
			State = 102;
			expr(0);
			State = 103;
			Match(RPAREN);
			State = 104;
			Match(LBRACE);
			State = 106;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				{
				State = 105;
				statement();
				}
				}
				State = 108;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( (((_la) & ~0x3f) == 0 && ((1L << _la) & 17592186045298L) != 0) );
			State = 110;
			Match(RBRACE);
			State = 125;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==ELIF) {
				{
				{
				State = 111;
				Match(ELIF);
				State = 112;
				Match(LPAREN);
				State = 113;
				expr(0);
				State = 114;
				Match(RPAREN);
				State = 115;
				Match(LBRACE);
				State = 117;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				do {
					{
					{
					State = 116;
					statement();
					}
					}
					State = 119;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				} while ( (((_la) & ~0x3f) == 0 && ((1L << _la) & 17592186045298L) != 0) );
				State = 121;
				Match(RBRACE);
				}
				}
				State = 127;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 137;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==ELSE) {
				{
				State = 128;
				Match(ELSE);
				State = 129;
				Match(LBRACE);
				State = 131;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				do {
					{
					{
					State = 130;
					statement();
					}
					}
					State = 133;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				} while ( (((_la) & ~0x3f) == 0 && ((1L << _la) & 17592186045298L) != 0) );
				State = 135;
				Match(RBRACE);
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class LoopContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode WHILE() { return GetToken(LavenderParser.WHILE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LPAREN() { return GetToken(LavenderParser.LPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RPAREN() { return GetToken(LavenderParser.RPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LBRACE() { return GetToken(LavenderParser.LBRACE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RBRACE() { return GetToken(LavenderParser.RBRACE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public StatementContext[] statement() {
			return GetRuleContexts<StatementContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public StatementContext statement(int i) {
			return GetRuleContext<StatementContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DO() { return GetToken(LavenderParser.DO, 0); }
		public LoopContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_loop; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ILavenderListener typedListener = listener as ILavenderListener;
			if (typedListener != null) typedListener.EnterLoop(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ILavenderListener typedListener = listener as ILavenderListener;
			if (typedListener != null) typedListener.ExitLoop(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILavenderVisitor<TResult> typedVisitor = visitor as ILavenderVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitLoop(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public LoopContext loop() {
		LoopContext _localctx = new LoopContext(Context, State);
		EnterRule(_localctx, 14, RULE_loop);
		int _la;
		try {
			State = 164;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case WHILE:
				EnterOuterAlt(_localctx, 1);
				{
				State = 139;
				Match(WHILE);
				State = 140;
				Match(LPAREN);
				State = 141;
				expr(0);
				State = 142;
				Match(RPAREN);
				State = 143;
				Match(LBRACE);
				State = 145;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				do {
					{
					{
					State = 144;
					statement();
					}
					}
					State = 147;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				} while ( (((_la) & ~0x3f) == 0 && ((1L << _la) & 17592186045298L) != 0) );
				State = 149;
				Match(RBRACE);
				}
				break;
			case DO:
				EnterOuterAlt(_localctx, 2);
				{
				State = 151;
				Match(DO);
				State = 152;
				Match(LBRACE);
				State = 154;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				do {
					{
					{
					State = 153;
					statement();
					}
					}
					State = 156;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				} while ( (((_la) & ~0x3f) == 0 && ((1L << _la) & 17592186045298L) != 0) );
				State = 158;
				Match(RBRACE);
				State = 159;
				Match(WHILE);
				State = 160;
				Match(LPAREN);
				State = 161;
				expr(0);
				State = 162;
				Match(RPAREN);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class CommandStatementContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode PRINT() { return GetToken(LavenderParser.PRINT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LPAREN() { return GetToken(LavenderParser.LPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RPAREN() { return GetToken(LavenderParser.RPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SEMI() { return GetToken(LavenderParser.SEMI, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] STRING() { return GetTokens(LavenderParser.STRING); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRING(int i) {
			return GetToken(LavenderParser.STRING, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] CHAR() { return GetTokens(LavenderParser.CHAR); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CHAR(int i) {
			return GetToken(LavenderParser.CHAR, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] IDENTIFY() { return GetTokens(LavenderParser.IDENTIFY); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENTIFY(int i) {
			return GetToken(LavenderParser.IDENTIFY, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode FUNCTION() { return GetToken(LavenderParser.FUNCTION, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LBRACE() { return GetToken(LavenderParser.LBRACE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RBRACE() { return GetToken(LavenderParser.RBRACE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public StatementContext[] statement() {
			return GetRuleContexts<StatementContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public StatementContext statement(int i) {
			return GetRuleContext<StatementContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] COMMA() { return GetTokens(LavenderParser.COMMA); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COMMA(int i) {
			return GetToken(LavenderParser.COMMA, i);
		}
		public CommandStatementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_commandStatement; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ILavenderListener typedListener = listener as ILavenderListener;
			if (typedListener != null) typedListener.EnterCommandStatement(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ILavenderListener typedListener = listener as ILavenderListener;
			if (typedListener != null) typedListener.ExitCommandStatement(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ILavenderVisitor<TResult> typedVisitor = visitor as ILavenderVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCommandStatement(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public CommandStatementContext commandStatement() {
		CommandStatementContext _localctx = new CommandStatementContext(Context, State);
		EnterRule(_localctx, 16, RULE_commandStatement);
		int _la;
		try {
			State = 201;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case PRINT:
				EnterOuterAlt(_localctx, 1);
				{
				State = 166;
				Match(PRINT);
				State = 167;
				Match(LPAREN);
				State = 174;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while ((((_la) & ~0x3f) == 0 && ((1L << _la) & 18966609117184L) != 0)) {
					{
					State = 172;
					ErrorHandler.Sync(this);
					switch ( Interpreter.AdaptivePredict(TokenStream,16,Context) ) {
					case 1:
						{
						State = 168;
						Match(STRING);
						}
						break;
					case 2:
						{
						State = 169;
						Match(CHAR);
						}
						break;
					case 3:
						{
						State = 170;
						Match(IDENTIFY);
						}
						break;
					case 4:
						{
						State = 171;
						expr(0);
						}
						break;
					}
					}
					State = 176;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				State = 177;
				Match(RPAREN);
				State = 178;
				Match(SEMI);
				}
				break;
			case FUNCTION:
				EnterOuterAlt(_localctx, 2);
				{
				State = 179;
				Match(FUNCTION);
				State = 180;
				Match(IDENTIFY);
				State = 181;
				Match(LPAREN);
				State = 190;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				if (_la==IDENTIFY) {
					{
					State = 182;
					Match(IDENTIFY);
					State = 187;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
					while (_la==COMMA) {
						{
						{
						State = 183;
						Match(COMMA);
						State = 184;
						Match(IDENTIFY);
						}
						}
						State = 189;
						ErrorHandler.Sync(this);
						_la = TokenStream.LA(1);
					}
					}
				}

				State = 192;
				Match(RPAREN);
				State = 193;
				Match(LBRACE);
				State = 195;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				do {
					{
					{
					State = 194;
					statement();
					}
					}
					State = 197;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				} while ( (((_la) & ~0x3f) == 0 && ((1L << _la) & 17592186045298L) != 0) );
				State = 199;
				Match(RBRACE);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public override bool Sempred(RuleContext _localctx, int ruleIndex, int predIndex) {
		switch (ruleIndex) {
		case 2: return expr_sempred((ExprContext)_localctx, predIndex);
		}
		return true;
	}
	private bool expr_sempred(ExprContext _localctx, int predIndex) {
		switch (predIndex) {
		case 0: return Precpred(Context, 4);
		case 1: return Precpred(Context, 3);
		case 2: return Precpred(Context, 2);
		case 3: return Precpred(Context, 1);
		}
		return true;
	}

	private static int[] _serializedATN = {
		4,1,47,204,2,0,7,0,2,1,7,1,2,2,7,2,2,3,7,3,2,4,7,4,2,5,7,5,2,6,7,6,2,7,
		7,7,2,8,7,8,1,0,4,0,20,8,0,11,0,12,0,21,1,0,1,0,1,1,1,1,1,1,1,1,1,1,3,
		1,31,8,1,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,
		2,1,2,1,2,1,2,1,2,1,2,1,2,3,2,55,8,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,
		2,1,2,1,2,1,2,5,2,69,8,2,10,2,12,2,72,9,2,1,3,1,3,1,3,1,3,3,3,78,8,3,1,
		3,1,3,1,4,1,4,1,4,1,4,1,4,1,5,1,5,1,5,1,5,1,5,5,5,92,8,5,10,5,12,5,95,
		9,5,3,5,97,8,5,1,5,1,5,1,6,1,6,1,6,1,6,1,6,1,6,4,6,107,8,6,11,6,12,6,108,
		1,6,1,6,1,6,1,6,1,6,1,6,1,6,4,6,118,8,6,11,6,12,6,119,1,6,1,6,5,6,124,
		8,6,10,6,12,6,127,9,6,1,6,1,6,1,6,4,6,132,8,6,11,6,12,6,133,1,6,1,6,3,
		6,138,8,6,1,7,1,7,1,7,1,7,1,7,1,7,4,7,146,8,7,11,7,12,7,147,1,7,1,7,1,
		7,1,7,1,7,4,7,155,8,7,11,7,12,7,156,1,7,1,7,1,7,1,7,1,7,1,7,3,7,165,8,
		7,1,8,1,8,1,8,1,8,1,8,1,8,5,8,173,8,8,10,8,12,8,176,9,8,1,8,1,8,1,8,1,
		8,1,8,1,8,1,8,1,8,5,8,186,8,8,10,8,12,8,189,9,8,3,8,191,8,8,1,8,1,8,1,
		8,4,8,196,8,8,11,8,12,8,197,1,8,1,8,3,8,202,8,8,1,8,0,1,4,9,0,2,4,6,8,
		10,12,14,16,0,4,1,0,27,28,1,0,25,26,1,0,31,32,1,0,34,37,236,0,19,1,0,0,
		0,2,30,1,0,0,0,4,54,1,0,0,0,6,73,1,0,0,0,8,81,1,0,0,0,10,86,1,0,0,0,12,
		100,1,0,0,0,14,164,1,0,0,0,16,201,1,0,0,0,18,20,3,2,1,0,19,18,1,0,0,0,
		20,21,1,0,0,0,21,19,1,0,0,0,21,22,1,0,0,0,22,23,1,0,0,0,23,24,5,0,0,1,
		24,1,1,0,0,0,25,31,3,6,3,0,26,31,3,8,4,0,27,31,3,12,6,0,28,31,3,14,7,0,
		29,31,3,16,8,0,30,25,1,0,0,0,30,26,1,0,0,0,30,27,1,0,0,0,30,28,1,0,0,0,
		30,29,1,0,0,0,31,3,1,0,0,0,32,33,6,2,-1,0,33,55,3,10,5,0,34,55,5,15,0,
		0,35,55,5,16,0,0,36,55,5,17,0,0,37,55,5,18,0,0,38,55,5,19,0,0,39,55,5,
		20,0,0,40,55,5,14,0,0,41,55,5,21,0,0,42,55,5,22,0,0,43,55,5,23,0,0,44,
		55,5,24,0,0,45,55,5,44,0,0,46,47,5,38,0,0,47,48,3,4,2,0,48,49,5,39,0,0,
		49,55,1,0,0,0,50,51,5,40,0,0,51,52,3,4,2,0,52,53,5,41,0,0,53,55,1,0,0,
		0,54,32,1,0,0,0,54,34,1,0,0,0,54,35,1,0,0,0,54,36,1,0,0,0,54,37,1,0,0,
		0,54,38,1,0,0,0,54,39,1,0,0,0,54,40,1,0,0,0,54,41,1,0,0,0,54,42,1,0,0,
		0,54,43,1,0,0,0,54,44,1,0,0,0,54,45,1,0,0,0,54,46,1,0,0,0,54,50,1,0,0,
		0,55,70,1,0,0,0,56,57,10,4,0,0,57,58,7,0,0,0,58,69,3,4,2,5,59,60,10,3,
		0,0,60,61,7,1,0,0,61,69,3,4,2,4,62,63,10,2,0,0,63,64,7,2,0,0,64,69,3,4,
		2,3,65,66,10,1,0,0,66,67,7,3,0,0,67,69,3,4,2,2,68,56,1,0,0,0,68,59,1,0,
		0,0,68,62,1,0,0,0,68,65,1,0,0,0,69,72,1,0,0,0,70,68,1,0,0,0,70,71,1,0,
		0,0,71,5,1,0,0,0,72,70,1,0,0,0,73,74,5,8,0,0,74,77,5,44,0,0,75,76,5,33,
		0,0,76,78,3,4,2,0,77,75,1,0,0,0,77,78,1,0,0,0,78,79,1,0,0,0,79,80,5,42,
		0,0,80,7,1,0,0,0,81,82,5,44,0,0,82,83,5,33,0,0,83,84,3,4,2,0,84,85,5,42,
		0,0,85,9,1,0,0,0,86,87,5,44,0,0,87,96,5,38,0,0,88,93,3,4,2,0,89,90,5,43,
		0,0,90,92,3,4,2,0,91,89,1,0,0,0,92,95,1,0,0,0,93,91,1,0,0,0,93,94,1,0,
		0,0,94,97,1,0,0,0,95,93,1,0,0,0,96,88,1,0,0,0,96,97,1,0,0,0,97,98,1,0,
		0,0,98,99,5,39,0,0,99,11,1,0,0,0,100,101,5,1,0,0,101,102,5,38,0,0,102,
		103,3,4,2,0,103,104,5,39,0,0,104,106,5,40,0,0,105,107,3,2,1,0,106,105,
		1,0,0,0,107,108,1,0,0,0,108,106,1,0,0,0,108,109,1,0,0,0,109,110,1,0,0,
		0,110,125,5,41,0,0,111,112,5,2,0,0,112,113,5,38,0,0,113,114,3,4,2,0,114,
		115,5,39,0,0,115,117,5,40,0,0,116,118,3,2,1,0,117,116,1,0,0,0,118,119,
		1,0,0,0,119,117,1,0,0,0,119,120,1,0,0,0,120,121,1,0,0,0,121,122,5,41,0,
		0,122,124,1,0,0,0,123,111,1,0,0,0,124,127,1,0,0,0,125,123,1,0,0,0,125,
		126,1,0,0,0,126,137,1,0,0,0,127,125,1,0,0,0,128,129,5,3,0,0,129,131,5,
		40,0,0,130,132,3,2,1,0,131,130,1,0,0,0,132,133,1,0,0,0,133,131,1,0,0,0,
		133,134,1,0,0,0,134,135,1,0,0,0,135,136,5,41,0,0,136,138,1,0,0,0,137,128,
		1,0,0,0,137,138,1,0,0,0,138,13,1,0,0,0,139,140,5,5,0,0,140,141,5,38,0,
		0,141,142,3,4,2,0,142,143,5,39,0,0,143,145,5,40,0,0,144,146,3,2,1,0,145,
		144,1,0,0,0,146,147,1,0,0,0,147,145,1,0,0,0,147,148,1,0,0,0,148,149,1,
		0,0,0,149,150,5,41,0,0,150,165,1,0,0,0,151,152,5,4,0,0,152,154,5,40,0,
		0,153,155,3,2,1,0,154,153,1,0,0,0,155,156,1,0,0,0,156,154,1,0,0,0,156,
		157,1,0,0,0,157,158,1,0,0,0,158,159,5,41,0,0,159,160,5,5,0,0,160,161,5,
		38,0,0,161,162,3,4,2,0,162,163,5,39,0,0,163,165,1,0,0,0,164,139,1,0,0,
		0,164,151,1,0,0,0,165,15,1,0,0,0,166,167,5,6,0,0,167,174,5,38,0,0,168,
		173,5,19,0,0,169,173,5,20,0,0,170,173,5,44,0,0,171,173,3,4,2,0,172,168,
		1,0,0,0,172,169,1,0,0,0,172,170,1,0,0,0,172,171,1,0,0,0,173,176,1,0,0,
		0,174,172,1,0,0,0,174,175,1,0,0,0,175,177,1,0,0,0,176,174,1,0,0,0,177,
		178,5,39,0,0,178,202,5,42,0,0,179,180,5,9,0,0,180,181,5,44,0,0,181,190,
		5,38,0,0,182,187,5,44,0,0,183,184,5,43,0,0,184,186,5,44,0,0,185,183,1,
		0,0,0,186,189,1,0,0,0,187,185,1,0,0,0,187,188,1,0,0,0,188,191,1,0,0,0,
		189,187,1,0,0,0,190,182,1,0,0,0,190,191,1,0,0,0,191,192,1,0,0,0,192,193,
		5,39,0,0,193,195,5,40,0,0,194,196,3,2,1,0,195,194,1,0,0,0,196,197,1,0,
		0,0,197,195,1,0,0,0,197,198,1,0,0,0,198,199,1,0,0,0,199,200,5,41,0,0,200,
		202,1,0,0,0,201,166,1,0,0,0,201,179,1,0,0,0,202,17,1,0,0,0,22,21,30,54,
		68,70,77,93,96,108,119,125,133,137,147,156,164,172,174,187,190,197,201
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
