"""
(C) COPYRIGHT 2026 EXcellent TechStacks - All Rights Reserved.

Domain models for the C-Programming-Language embedded support.
Decoupled from libclang, Qt, and file system operations.
"""

from dataclasses import dataclass, field
from typing import List, Optional


@dataclass
class CContext:
    """
    Immutable snapshot of the editor's state for the C source file.

    Includes compilation arguments so libclang can correctly parse
    target-specific headers, cross-compiler include paths, and
    preprocessor macros for Clang targets.
    """

    source_code: str
    line: int
    col: int
    file_path: Optional[str] = None
    compile_args: List[str] = field(default_factory=list)


@dataclass(frozen=True)
class ParameterInfo:
    """
    Represents a single parameter in a C function or macro signature.
    """

    name: str
    type_str: str
    default_value: Optional[str] = None


@dataclass(frozen=True)
class HoverDetails:
    """
    Documentation and signature details extracted from libclang ASt
    or Doxygen comments.
    """

    name: str
    kind: str
    signature: str
    parameters: List[ParameterInfo] = field(default_factory=list)
    return_type: Optional[str] = None
    docstring: Optional[str] = None


@dataclass(frozen=True)
class DefinitionLocation:
    """
    Target location details for GoTo Definition and Find References
    requests.
    """

    file_path: Optional[str]
    line: int  # 1-indexed
    column: int  # 1-indexed
    context_line: Optional[str] = None


@dataclass(frozen=True)
class CompletionDetails:
    """
    One autocompletion suggestion generated by libclang.
    """

    text: str
    insert_text: str = ""
    kind: str = ""
    signature: str = ""


@dataclass(frozen=True)
class CDiagnostic:
    """
    Represents a compiler error, warning, or note from Clang
    frontend.
    """

    line: int
    start_col: int
    end_col: int
    severity: str
    message: str
    color: str
