"""
(C) COPYRIGHT 2026 EXcellent TechStacks - All Rights Reserved.

Dynamic plugin registration system for DreamStudio languages.

Discovers language plugins from two sources:
- ``editor/Ironica/keywords/*.json`` — keyword/style configs (syntax highlighting)
- ``editor/Ironica/plugins/*/provider.py`` — provider factories (intelligence)

The registry file ``~/.dreamstudio/plugins/plugins.json`` is the single
source of truth.  If it is missing or corrupt, it is auto-generated by
scanning the filesystem.

This module is the only file in the plugin package that imports from
the editor core — it keeps provider code fully decoupled.
"""

import os
import json
import importlib
import logging
from pathlib import Path
from typing import Any, Optional

from editor.Ironica.language_engine import LanguageRegistry
from editor.utils.notifications.notification_manager import get_notification_manager

logger = logging.getLogger(__name__)

# ------------------------------------------------------------------
# Path helpers
# ------------------------------------------------------------------

_IRONICA_DIR = os.path.normpath(
    os.path.join(os.path.dirname(__file__), "..")
)
_KEYWORDS_DIR = os.path.join(_IRONICA_DIR, "keywords")
_PLUGINS_PKG_DIR = os.path.dirname(__file__)

_DREAMSTUDIO_HOME = Path.home() / ".dreamstudio"
_PLUGINS_JSON_PATH = _DREAMSTUDIO_HOME / "plugins" / "plugins.json"

_PLUGINS_JSON_VERSION = 1


# ------------------------------------------------------------------
# Auto-discovery
# ------------------------------------------------------------------


def _scan_keywords() -> dict[str, str]:
    """Scan ``keywords/*.json`` and return ``{lang_name: relative_json_path}``.

    Paths are stored relative to the Ironica directory so that
    ``plugins.json`` is portable across machines and users.
    """
    result: dict[str, str] = {}
    kw_dir = Path(_KEYWORDS_DIR)
    if not kw_dir.is_dir():
        return result
    for json_file in sorted(kw_dir.glob("*.json")):
        try:
            with open(json_file, "r", encoding="utf-8") as fh:
                data = json.load(fh)
            lang = data.get("lang")
            if lang and isinstance(lang, str):
                result[lang] = os.path.relpath(json_file, _IRONICA_DIR)
        except (json.JSONDecodeError, OSError) as exc:
            logger.warning("Skipping invalid keyword file %s: %s", json_file, exc)
    return result


def _scan_providers() -> dict[str, str]:
    """Scan ``plugins/*/provider.py`` and return ``{lang: dotted_factory_path}``."""
    result: dict[str, str] = {}
    plugins_dir = Path(_PLUGINS_PKG_DIR)
    if not plugins_dir.is_dir():
        return result
    for child in sorted(plugins_dir.iterdir()):
        if not child.is_dir():
            continue
        if child.name.startswith("_"):
            continue
        provider_file = child / "provider.py"
        if provider_file.is_file():
            dotted = f"editor.Ironica.plugins.{child.name}.provider.create_provider"
            result[child.name] = dotted
    return result


def _auto_discover() -> dict[str, Any]:
    """Build a plugins config dict by scanning the filesystem.

    Returns:
        A dict with ``"version"`` and ``"plugins"`` keys, suitable for
        writing to ``plugins.json``.
    """
    keywords = _scan_keywords()
    providers = _scan_providers()

    plugins: dict[str, dict[str, str]] = {}
    for lang in sorted(set(keywords) | set(providers)):
        entry: dict[str, str] = {}
        if lang in keywords:
            entry["keywords"] = keywords[lang]
        if lang in providers:
            entry["provider"] = providers[lang]
        plugins[lang] = entry

    return {"version": _PLUGINS_JSON_VERSION, "plugins": plugins}


# ------------------------------------------------------------------
# Config management
# ------------------------------------------------------------------


def _ensure_plugins_json() -> dict[str, Any]:
    """Auto-discover plugins and write ``plugins.json``.

    Returns:
        The newly written config dict.
    """
    config = _auto_discover()
    try:
        _PLUGINS_JSON_PATH.parent.mkdir(parents=True, exist_ok=True)
        with open(_PLUGINS_JSON_PATH, "w", encoding="utf-8") as fh:
            json.dump(config, fh, indent=4)
        logger.info(
            "Auto-generated plugins.json with %d languages",
            len(config.get("plugins", {})),
        )
    except OSError as exc:
        logger.error("Failed to write plugins.json: %s", exc)
    return config


def load_plugins_config() -> dict[str, Any]:
    """Load and validate the plugins config, auto-creating if needed.

    Returns:
        The validated config dict.
    """
    if not _PLUGINS_JSON_PATH.is_file():
        logger.info("plugins.json not found, auto-discovering plugins")
        return _ensure_plugins_json()

    try:
        with open(_PLUGINS_JSON_PATH, "r", encoding="utf-8") as fh:
            raw = json.load(fh)
    except (json.JSONDecodeError, OSError) as exc:
        logger.warning("plugins.json is corrupt, regenerating: %s", exc)
        return _ensure_plugins_json()

    if not isinstance(raw, dict) or "plugins" not in raw:
        logger.warning("plugins.json has invalid structure, regenerating")
        return _ensure_plugins_json()

    return raw


# ------------------------------------------------------------------
# Provider import
# ------------------------------------------------------------------


def _import_factory(dotted_path: str) -> Optional[Any]:
    """Import and return the callable at *dotted_path*.

    Returns:
        The factory function, or ``None`` if import fails.
    """
    try:
        module_path, _, attr_name = dotted_path.rpartition(".")
        module = importlib.import_module(module_path)
        return getattr(module, attr_name, None)
    except Exception as exc:
        logger.error("Failed to import provider factory %s: %s", dotted_path, exc)
        return None


# ------------------------------------------------------------------
# Registration
# ------------------------------------------------------------------


def _register_one(lang: str, spec: dict[str, str]) -> tuple[bool, Optional[str]]:
    """Register a single language from its config spec.

    Args:
        lang: Language identifier (e.g. ``"python"``).
        spec: Plugin spec with ``"keywords"`` and optional ``"provider"`` paths.

    Returns:
        ``(success, warning_message_or_None)``
    """
    json_path = spec.get("keywords", "")
    provider_path = spec.get("provider", "")

    if not json_path:
        return False, f"{lang}: no keywords path in spec"

    # Resolve relative paths against the Ironica directory.
    if not os.path.isabs(json_path):
        json_path = os.path.join(_IRONICA_DIR, json_path)

    provider = None
    if provider_path:
        factory = _import_factory(provider_path)
        if factory is not None:
            try:
                provider = factory()
            except Exception as exc:
                logger.error(
                    "Provider factory for %r failed: %s", lang, exc
                )
                return False, f"{lang}: provider factory failed: {exc}"

    try:
        success = LanguageRegistry.register_language(json_path, provider)
    except Exception as exc:
        logger.error("Failed to register language %r: %s", lang, exc)
        return False, f"{lang}: registration raised {exc}"

    label = lang.capitalize()
    if success:
        logger.info("Language plugin registered: %s", lang)
        get_notification_manager().add_success(
            f"{label} Support Loaded",
            f"{label} language support initialized successfully.",
            "Plugins",
        )
        return True, None
    else:
        msg = f"{label} language plugin registration returned False"
        logger.warning(msg)
        get_notification_manager().add_warning(
            f"{label} Plugin Warning",
            f"{label} language plugin could not be registered. "
            "Syntax highlighting may be unavailable.",
            "Plugins",
        )
        return False, msg


def register_all_languages() -> list[str]:
    """Register every language defined in ``plugins.json``.

    Languages are loaded in alphabetical order.  If ``plugins.json``
    is missing, it is auto-generated by scanning the filesystem.

    Returns:
        A list of warning messages (empty on full success).
    """
    config = load_plugins_config()
    plugins = config.get("plugins", {})
    warnings: list[str] = []

    for lang in sorted(plugins):
        ok, warn = _register_one(lang, plugins[lang])
        if warn:
            warnings.append(warn)

    return warnings


# ------------------------------------------------------------------
# Legacy API (used by tests)
# ------------------------------------------------------------------


def register_python_language() -> bool:
    """Register the Python language with the LanguageRegistry.

    Loads the Python keyword/style JSON config and attaches a fully
    wired ``PythonLanguageProvider`` backed by Jedi.

    Returns:
        ``True`` on success, ``False`` on any failure.
    """
    try:
        from editor.Ironica.plugins.python.provider import create_provider

        provider = create_provider()
        json_path = os.path.join(_KEYWORDS_DIR, "python.json")

        success = LanguageRegistry.register_language(json_path, provider)
        if success:
            logger.info("Python language plugin registered successfully")
            get_notification_manager().add_success(
                "Python Support Loaded",
                "Python language support initialized successfully.",
                "Plugins",
            )
        else:
            logger.warning("Python language plugin registration returned False")
            get_notification_manager().add_warning(
                "Python Plugin Warning",
                "Python language plugin could not be registered. "
                "Code intelligence may be unavailable.",
                "Plugins",
            )
        return success

    except Exception as exc:
        logger.error("Failed to register Python language plugin: %s", exc)
        get_notification_manager().add_error(
            "Python Plugin Error",
            f"Python language plugin failed to initialize: {exc}. "
            "Code intelligence disabled.",
            "Plugins",
        )
        return False


def unregister_python_language() -> bool:
    """Remove the Python language from the LanguageRegistry.

    Returns:
        ``True`` if Python was registered and has been removed.
    """
    return LanguageRegistry.unregister_language("python")
